---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alb-ingress
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default

