---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: microservices-demo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/kubernetes/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: microservices-demo
  targetNamespace: default

